### ISSUE TITLE
As a researcher, I want to be able to use metadata submitter API so I can use the service programmatically

### ISSUE THREAD

**Issue by genie9** [CSCfi/metadata-submitter#504]
#### Describe the user story

Metadata submitter API has some issues before it can be used independently from the frontend. 

#### Tasks:
List of tasks needed for this user story. The technical description is in the tasks. Additional information, for example, a prototype, Figma files, and pictures are linked here. 
- [x] As an SD-Submit API user, I want to be able to submit DOI information through a dedicated endpoint so it would simplify my work
- [x] As an SD-Submit API user, I want to have access to SD Submit API documentation so I would understand how to create submissions using API
- [x] As a researcher I need to see API documentation with schemas up to date so I know what needs to be sent with a request body
- [x] As an SD Submit API user I need to know how submission information is updated so I can change the name and description of my submission
- [x] As a SD Submit API user I need to be able to authenticate through API login.

#### Testing 
Description of how the testing will be done.  

#### Definition of Done
SD Submit API users have the information to perform all needed actions for metadata submission through an API.

**Comment by blankdots** [comment]
i am not sure researchers what to do that, however other 3rd parties or collaborators might want to do that.
