### ISSUE TITLE
As a API submitter, I want to validate connections between metadata objects so that the dataset is correct and complete

### ISSUE THREAD

**Issue by viklund** [CSCfi/metadata-submitter#510]
#### Describe the user story

The different metadata objects (images, datasets, studies and so on) references each other with aliases. We need to make sure that these references are correct before proceeding with a submission.

The [metadata schema](https://github.com/imi-bigpicture/metadata-schema) specifies these references. [Here](https://github.com/imi-bigpicture/metadata-schema/blob/v0.1.1/src/BP.dataset.xsd#L45-L58) a dataset references images for example.

An example of a reference is can be found in the test metadata between 
[this dataset](https://github.com/CSCfi/metadata-submitter/blob/develop/tests/test_files/bpdataset/template_dataset.xml#L25) and [this image](https://github.com/CSCfi/metadata-submitter/blob/develop/tests/test_files/image/images_single.xml#L2).

#### Tasks:
- [ ] Write functionality to check cross references between metadata objects
- [ ] Get more example files so we are sure we have all possible connections in the test metadata
- [ ] Figure out when this functionality should be triggered

#### Testing 
Description how the testing will be done.  

#### Definition of Done
Given uploaded metadata when I do `some action` then I expect an 200 Ok or some error code together with information about what was incorrect.
