### ISSUE TITLE
Lint JSON schemas

### ISSUE THREAD

**Issue by csc-felipe** [CSCfi/metadata-submitter#581]
#### Proposed solution

Schemas are a central part on which metadata submitter is built on, however, so far we don't check that the JSON schemas conform to the specification, or to which specification.

In #578, a new `pre-commit` check was added, and we can use its `check-metaschema` to validate our schemas.

#### Tasks
- [x] Use `check-metaschema` pre-commit hook

```
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.18.2
  hooks:
    - id: check-metaschema
      files: ^metadata_backend/helpers/schemas/.*\.json$
```
- [x] Fix any discovered issues
- [x] Add a `$schema` attribute to indicate the schema version of the document
- [x] Run it in Github CI to continuously validate our schemas.

#### DoD (Definition of Done)

Continuously assert that the JSON schemas conforms with the specification.

#### Testing

New tests pass
