### ISSUE TITLE
Unify DAC and policy implementations

### ISSUE THREAD

**Issue by csc-felipe** [CSCfi/metadata-submitter#588]
#### Proposed solution

Currently we have two distinct implementations for DAC and policy.
1. From EGA schema
2. From REMS

and they are not connected in any way.

#### Tasks
- [ ] Design unification for both implementations
The proposed solution would be to:
  1. Rename, in the submission schema `dac` to `rems` https://github.com/CSCfi/metadata-submitter/pull/648
  2. Accept EGA XML and validate against data that lives in REMS - adding EGA DAC object to DB, and configuring the `submission.rems` field
  3. When setting REMS fields through the API (including front-end), create (or replace) the EGA DAC object to DB. #532

- [ ] Make code changes
- [ ] Update tests
- [ ] Create ticket for the frontend

#### DoD (Definition of Done)

DAC and policy implementations are unified, and interchangeable.
