### ISSUE TITLE
Proper unit and integration tests for Files

### ISSUE THREAD

**Issue by csc-felipe** [CSCfi/metadata-submitter#629]
#### Description

Files endpoint were added in #627, but didn't get enough tests. We should tests that the endpoint returns correct files given pre-existing files in MongoDB.

#### Tasks
- [ ] Files in more than one project
- [ ] Listing files for a project returns only the desired files
- [ ] Add files to a submission
- [ ] Reading files in a submission gives the correct files
- [ ] Remove file from a submission
- [ ] Update file in a submission

#### DoD (Definition of Done)

Test multiple usage cases and methods.
